---
kind: pipeline
name: default

steps:
  - name: Run rspec for each library
    image: ruby:2.6
    commands:
      - make test

  - name: Release gems
    image: ruby:2.6
    environment:
      GEM_CREDENTIALS:
        from_secret: gem_credentials
    commands:
      - mkdir -p ~/.gem
      - echo $GEM_CREDENTIALS | base64 -d > ~/.gem/credentials
      - chmod 0600 ~/.gem/credentials
      - make release
    when:
      branch:
        - master
        - "*-stable"

trigger:
  event:
    - push
